# GitHub Pages Configuration
plugins:
  - jekyll-sitemap

# Include files
include:
  - _headers
  - .htaccess
  - robots.txt
  - sitemap.xml

# Exclude files
exclude:
  - README.md
  - .gitignore
  - .DS_Store

# MIME types for GitHub Pages
plugins:
  - jekyll-sitemap
